### ISSUE TITLE
  bug by install_github("datamicroarry","ramey")

### ISSUE THREAD

**Issue by SHASHANKKS** [ramhiser/datamicroarray#17]
Dear Ramhiser,

i wanted to install Datamicroarry package , but unfortunately i always get an error.

It looks like this:
install.packages("devtools") # okay
devtools::install_github("ramey/datamicroarry") # but here:

Downloading github repo ramey/datamicroarry@master
Error in download(dest, src, auth) : client error: (404) Not Found
Could you help me on this?

With kind regards,
SHASHANK K S

**Comment by ramhiser** [comment]
Ah, nice catch. The instructions in the `README` file are incorrect. Instead, please use the following:

```r
devtools::install_github('ramhiser/datamicroarray')
```

**Comment by ramhiser** [comment]
I will update the `README` accordingly.

**Comment by SHASHANKKS** [comment]
Thank You for the timely help Ramhiser
